apiVersion: v1
kind: Pod
metadata:
  labels:
    cherry-syte.service: app
  name: app
spec:
  containers:
    - image: j00mz/cherry-syte:latest
      name: app
      ports:
        - containerPort: 5000
      livenessProbe:
        httpGet:
          path: /
          port: 5000
          httpHeaders:
          - name: Custom-Header
            value: Health Probe
        initialDelaySeconds: 3
        periodSeconds: 4
      resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
  restartPolicy: OnFailure
